name: CI
on:
  push:
    branches: [ "publish" ]
  workflow_dispatch:
permissions:
  id-token: write
  pages: write
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: Install Wasm and Files
        run: zig build wasm -Doptimize=ReleaseSmall
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: www
          path: zig-out/bin/webroot
          retention-days: 1
  deploy:
    needs: install
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download site files
        uses: actions/download-artifact@v4
        with:
          name: www
          path: public
      - name: Configure GitHub pages
        uses: actions/configure-pages@v5
      - name: Upload GitHub pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
